# coderabbit.yaml
project:
  name: Personal Portfolio Website
  root: ./portfolio
  context_file: PROJECT_CONTEXT.md
  description: >
    A modern, responsive personal portfolio website for a software engineer.
    Showcases projects, experience, skills, and contact info. Audience includes
    recruiters, hiring managers, and collaborators.

tech_stack:
  languages:
    - JavaScript (ES6+)
    - TypeScript
    - HTML5
    - CSS3
  frameworks:
    - React
    - Next.js
    - TailwindCSS
    - Framer Motion (optional)
    - MDX (optional)
  tools:
    - Vercel
    - GitHub
    - Figma
    - ESLint
    - Prettier

ai_integration:
  read_context_first: true
  follow_conventions: true
  update_context_on_change: true
  check_before_action:
    - structure_changes
    - dependencies_changes
    - test_or_doc_updates
    - stack_and_standard_consistency
  diff_mode: true
  human_review: true

workflow:
  steps:
    - load_context
    - scaffold_code
    - generate_tests
    - update_docs
    - suggest_context_changes
  conventions:
    code_format: ESLint + Prettier
    styling: TailwindCSS
    testing: Jest + React Testing Library
    commit_message_format: Conventional Commits
  mvp_scope:
    - landing_page_with_hero_about_projects_contact
    - responsive_design
    - hosted_on_vercel
